overrides:
  - files:
      - "**/*.java"
    options:
      trailingComma: none
      useTabs: true
      tabWidth: 2
      semi: false
      singleQuote: false
      printWidth: 120
      arrowParens: avoid
      endOfLine: auto
